### ISSUE TITLE
For EC encryption: Expected key type oct, got EC

### ISSUE THREAD

**Issue by CanD42** [latchset/jwcrypto#157] opened 2019-06-04 09:42 UTC
We use a signed and EC encrypted JWT generated by a java process which I can verify without problems with jwcrypto. However, when I try to generate such a token I run into the following problem:

```
    def _get_key(self, key, op):
        if not isinstance(key, JWK):
            raise ValueError('key is not a JWK object')
        if key.key_type != 'oct':
>           raise InvalidJWEKeyType('oct', key.key_type)
E           jwcrypto.common.InvalidJWEKeyType: Expected key type oct, got EC
```

Is this a bug or am I doing something wrong with following code:

```
private_idp_key_dict = {"kty": "EC", "crv": "P-256", "x": "...", "y": "...", "d": "...", "kid": "idp"}
public_sp_key_dict = {"kty": "EC", "crv": "P-256", "x": "...", "y": "...", "use": "enc", "kid": "sp"}
private_idp_key = jwk.JWK(**private_idp_key_dict)
public_sp_key = jwk.JWK(**public_sp_key_dict)

claims = {
	"sub": uid,
}
signed_token = jwt.JWT(header = {'alg': 'ES256'}, claims = claims)
signed_token.make_signed_token(private_idp_key)

encrypted_token = jwt.JWT(header = {'alg': 'A256KW', 'enc': 'A128CBC-HS256'}, claims = signed_token.serialize())
encrypted_token.make_encrypted_token(public_sp_key)
token = encrypted_token.serialize()
```

Thanks,
Daniel

**Comment by simo5** [comment] 2019-06-04 18:40
There are several errors in the code above.
- You are asking jwcrypto to encrypt the token with a symmetric key cipher but providing an EC key ?
- You are telling Jwcrypto to use AES 256 Key Wrap but the use a 128bit encryption scheme ?

If you want to use a public EC key to encrypto to, you probably want to use something like ECDH-ES (no key wrapping) or probably ECDH-ES+A128KW, if you want key wrapping.
You also probably want to match the key wrapping size with the actual key encryption size.

**Comment by simo5** [comment] 2019-06-04 18:44
Ah I see why you are using A256KW, I guess it is because you are using A128CBC-HS256 where half of the key is used for encryption and the other half for the MAC. You may want to consider using A128GCM instead toi keep keysizes consistent, But if you have to use A128CBC-HS256 then you'll have to use ECDH-ES+A256KW I think.

**Comment by simo5** [comment] 2019-06-06 17:25
I hope this explanation works for you, closing this issue as it is not a bug

**Closed by simo5** 2019-06-06 17:25 UTC
